config/routes.rb
Rails.application.routes.draw do
  get 'find_autos/show'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'autos#index'
  # Defines the root path route ("/")
  resources :autos do
    resources :comments
  end

  resources :profiles

  resources :find_autos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/auto.rb
class Auto < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :comments, :dependent => :destroy
  
  belongs_to :user

  validates :title, presence: true, length: {minimum: 3}
  validates :car_text, presence: true, length: {minimum: 0}
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :auto

  validates :body, presence: true, length: {minimum: 1}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :autos
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController

    def index
        @autos = Auto.all
    end

    def new
        @auto = Auto.new
    end

    def show
        @auto = Auto.find(params[:id])
    end

    def create
        @auto = Auto.new(:title => params[:title], :car_text => params[:auto], :user_id => current_user.id, :image => params[:image])

        if(@auto.save)
            redirect_to @auto
        else
            render 'new'
        end
    end

    def edit
        @auto = Auto.find(params[:id])
    end

    def update
        @auto = Auto.find(params[:id])
        if(@auto.update(:title => params[:title], :car_text => params[:car_text], :image => params[:image]))
            redirect_to @auto
        else
            render 'edit'
        end
    end

    def destroy
        @auto = Auto.find(params[:id])
        
        @auto.destroy
        redirect_to autos_path
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @auto = Auto.find(params[:auto_id])
        @comment = @auto.comments.create(:body => params[:body], :user_id => current_user.id, :auto_id => @auto.id)
        redirect_to auto_path(@auto)
    end
    
end

app/controllers/find_autos_controller.rb
class FindAutosController < ApplicationController
  
  def show
      @autos = Auto.where("title LIKE ?", "%" + Auto.sanitize_sql_like(params[:title]) + "%")
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def show
        @profile = User.find(params[:id])
    end

    def edit
        @profile = User.find(params[:id])
    end

    def update
        @profile = User.find(params[:id])
        @profile.update(:nickname => params[:nickname], :about_me => params[:about_me])

        redirect_to profile_path(@profile)
    end

end

app/helpers/Autos_helper.rb
module AutosHelper
end

app/helpers/add_auto_helper.rb
module AddAutoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/find_autos_helper.rb
module FindAutosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/autos/edit.html.erb
<h1 class="text-white">Изменение поста</h1>
    

    <div class="container text-white">
        <div class="col-md-9" >
            <%= form_for :auto, url: auto_path(@auto), html: {multipart: true}, method: :patch do |f|%>
                <%if(@auto.errors.any?)%>
                    <%@auto.errors.messages.each do |msg|%>
                        <div class="alert alert-danger">
                            <%= msg[1][0]%>
                        </div>
                    <%end%>
                <%end%>                
                <div class="mb-2">
                    <div class="mb-2 text-white">марка\модель\пробег:</div>
                    <%= text_field_tag :title, "#{@auto.title}", class: 'form-control' %> 
                    <%# <%= f.text_field(:title, {:class => 'form-control'}) %> 
                </div>
                <p> <%= image_tag @auto.image.url(:large), class: 'img-show' if @auto.image? %> </p>
                <%= file_field_tag :image %>
                <div class="mb-4">
                    <div class="mb-2">Коментарий:</div>
                    <%= text_area_tag :car_text, "#{@auto.car_text}", class: 'form-control' %> 
                </div>
                
                <%= submit_tag "Изменить", class: "btn btn-outline-danger" %>
            <%end%>
        </div>
        <div class="col-md-3"></div>
    </div>

app/views/autos/index.html.erb
<div class="container">
    <h2 style="color: red;">Все темы:</h2> 
</div>
<div class = "container" style="border-right: 3px solid red; padding-right:15px;">
    <div class="row">
    <% @autos.each do |auto| %>
            <div class = "col-md-4 text-left my-4 border border-dark bg-light">
                <%= link_to "#{auto.title}", auto_path(auto), class: "a"%>
                <br>
                <small> Автор: 
                <%if(User.find(auto.user_id).nickname)%>
                    <%=link_to "#{User.find(auto.user_id).nickname}", profile_path(User.find(auto.user_id)), class: "a" %>
                <%else%>
                    <%=link_to "#{User.find(auto.user_id).email}", profile_path(User.find(auto.user_id)), class: "a" %>
                <%end%>
                </small>
            </div>
            <div class = "col-md-8 text-left my-4 border border-dark bg-light">
                <%=link_to auto_path(auto) do%>
                    <div >
                    <%= link_to "#{auto.car_text}", auto_path(auto), class: "a"%>
                    </div>
                <%end%>
            </div>
            <div class = "col-md-0 text-left my-4 border border-dark bg-light">
                <%=link_to auto_path(auto) do%>
                    <div >
                    <%= image_tag auto.image.url(:thumb), class: 'img-show w-100' if auto.image? %>
                    </div>
                <%end%>
            </div>
    <% end%>
    </div>
</div>

app/views/autos/new.html.erb
<h1 style="margin-bottom: 30px; color: whitesmoke;">Создать пост</h1>
    

    <div class="container">
        <div class="col-md-9" style="border-right: 0px solid grey; padding-right:15px;">
            <%= form_for :auto, html: {multipart: true}, url: autos_path do |f|%>
                <%if @auto.errors.any?%>
                        <%@auto.errors.messages.each do |msg|%>
                            <div class="alert alert-danger">
                                <%= msg [1][0]%>
                            </div>
                        <%end%>
                <%end%>  
                <div class="mb-2">
                    <div class="mb-2 text-white">Марка\модель\пробег</div>
                     <%= text_field_tag :title, "", class: 'form-control' %>
                </div>
                <div class="mb-4 text-white">
                    <div class="mb-2 text-white">Коментарий</div>
                    <%= text_area_tag :auto, "", class: 'form-control' %>
                </div>
                    <%# <button type="button" class="btn btn-outline-success">Добавить изображения</button> %>
                 <%= file_field_tag :image %>
                <%= submit_tag "Опубликовать", class: "btn btn-outline-danger" %>
            <%end%>
        </div>
        <div class="col-md-3 text-white"></div>
    </div>

    

app/views/autos/show.html.erb
 <div class="container">
    <div class="row">
        <div class="col-md-9 text-white" >
            <h1> <%= @auto.title%> </h1>
            <small> 
                <%= link_to "#{User.find(@auto.user_id).email}", profile_path(User.find(@auto.user_id)), class: "text-white"%> , 
                        <time><%= @auto.created_at.to_date.strftime("%d %B, %Y") %> </time>
                        <br>
                        <% if (current_user)%>
                            <% if (current_user.id == @auto.user_id)%>
                                <div class="btn-group" role="group" aria-label="Basic example" style="margin-bottom: 40px">
                                    <%= link_to "Редактировать", edit_auto_path(@auto), class: "btn btn-outline-success"%>
                                    <%= button_to "Удалить публикацию", auto_path(@auto), method: :delete, class: "btn btn-outline-danger"%>
                                </div>
                                <br>
                            <%end%>
                        <%end%>
            </small> 
            <p> <%= image_tag @auto.image.url, class: 'img-show w-100' if @auto.image? %> </p>
            <div style="overflow: clip;">
                <p> <%= @auto.car_text%> </p>
            </div>
            

            <h4>Комментарии:</h4>
                <hr>
                <h5>Добавить ответ</h5>
                    <%if(current_user)%>
                        <%= form_for([@auto, @auto.comments.build]) do |f|%>
                            <div class="mb-4"> 
                                <%= text_area_tag :body, "", class: 'form-control' %>
                            </div>
                            <%= submit_tag "Добавить", class: "btn btn-success" %> 
                        <%end%>
                    <%else%>
                        <a>Чтобы добавить ответ нужно</a> <%= link_to "авторизиваться", new_user_session_path%>
                    <%end%>
                </hr>
                <hr>
                    <h4>Все ответы </h4>
                    
                        <% @auto.comments.each do |comment| %>
                            <div class="alert alert-light">
                                <p> <strong> 
                                    <%if(comment.user_id)%>
                                        <%if(User.find(comment.user_id).nickname)%> 
                                            <%= User.find(comment.user_id).nickname%>, <time><%= comment.created_at.to_date.strftime("%d %B, %Y") %> </time>:
                                        <%else%>
                                            <%= User.find(comment.user_id).email%>, <time><%= comment.created_at.to_date.strftime("%d %B, %Y") %> </time>:
                                        <%end%> 
                                    <%end%> 
                                </strong>
                                    <%= comment.body%>
                                </p>
                            </div>
                        <% end%>
                </hr>
        </div>
    </div>
</div>

app/views/find_autos/show.html.erb
<div class="container" style=" color: red;">
    <h2>Найденные темы:</h2> 
</div>
<div class = "container" style=" color: whitesmoke;">
    <div class="row" style=" color: whitesmoke;">
    <%if (@autos).count > 0%>
        <% @autos.each do |auto| %>
            <div class = "col-md-12 text-left my-4" style=" color: whitesmoke;">
                    <%= link_to "#{auto.title}", auto_path(auto), class: "custom" %>
                    <br style="color: whitesmoke;">
                    <small style=" color: whitesmoke;"> Автор: 
                    <%if(User.find(auto.user_id).nickname)%>
                        <%=link_to "#{User.find(auto.user_id).nickname}", profile_path(User.find(auto.user_id)), class: "custom" %>
                    <%else%>
                        <%=link_to "#{User.find(auto.user_id).email}", profile_path(User.find(auto.user_id)), class: "custom" %>
                    <%end%>
                    </small>
                </div>
            
        <% end%>
    <%else%>
        <h3 style="color: grey" class="text-center">По вашему запросу ничего не найдено<br><br>
        <%=button_to "Вернуться на главную", root_path, class: "btn btn-outline-success", method: :get%></h3>
        
    <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zachet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application"%>
    <%= javascript_importmap_tags %>
    
  </head>

  <body style="background:black;">
          <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <div class="container-fluid">
              <div class="col-1">
              </div>
              <div class="col-1">
                <a class="navbar-brand text-white" href="http://localhost:3000/">Buy&Drive</a> 
              </div>
              <div class="col-2">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="float: letf">
                  <li class="nav-item">
                    <% if current_user %>
                      <a class="nav-link active" aria-current="page" href="/autos/new" style=" color: whitesmoke;"> Создать пост </a>
                    <% else%>
                      <a class="nav-link active" aria-current="page" href="/users/sign_in" style=" color: whitesmoke;"> Создать пост </a>
                    <% end%>
                  </li>
                  <% if current_user %>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" style=" color: whitesmoke;" data-bs-toggle="dropdown" aria-expanded="false">
                          <% if current_user.nickname%>
                            <%= current_user.nickname%>
                          <% else%>
                            <%= current_user.email%>
                          <% end%>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                         <li><%= link_to "Профиль", profile_path(User.find(current_user.id)), class: "dropdown-item"%> 
                        <li><%= link_to "Выйти", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "dropdown-item"%> </li>
                      </ul>
                    </li>
                  <% else%>
                    <li class="nav-item">
                      <a class="nav-link active text-white" aria-current="page" href="/users/sign_in", method: :delete, data: {turbo: false}>Войти</a> 
                    </li>
                  <% end%>
                </ul>
              </div>
              <div class="col-3">
                
              </div>
              <div class="col-4">
                <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                  <form action="/find_autos/show" method="get" class="d-flex">
                      <%= text_field_tag :title, "", class: 'form-control me-3' %>  
                      <%= submit_tag "Найти", class: "btn btn-outline-danger" %> 
                  </form>
                </div>
              </div>
              <div class="col-sm">
              </div>
            </div>
          </nav>
    <div class="container text-center">
      <p class="notice" style="color: red"><%= notice%> </p>
      <p class="alert" style="color: red"><%= alert%> </p>
    </div>

    
    <div class="container">  
      <%= yield %>
    </div>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/profiles/edit.html.erb
<h2 class="text-white"> Редактирование профиля</h2>
<%= form_for :profile, url: profile_path(@profile), method: :patch do |f|%>
        <%if(@profile.errors.any?)%>
            <%@profile.errors.full_messages.each do |msg|%>
                <div class="alert alert-danger">
                    <%= msg%>
                </div>
            <%end%>
        <%end%>
        <div class="mb-2 text-white">
            <div class="mb-2">Имя пользователя:</div>
             <%= text_field_tag :nickname, "#{@profile.nickname}", class: 'form-control' %> 
        </div>
        <div class="mb-4 text-white">
            <div class="mb-2 text-white">Машины во влаедении:</div>
             <%= text_area_tag :about_me, "#{@profile.about_me}", class: 'form-control' %> 
        </div>
        <%= submit_tag "Сохранить", class: "btn btn-danger" %>
    <%end%>

app/views/profiles/show.html.erb
<div style="margin-bottom: 50px">
<h4>
    <%if(@profile.nickname)%>
        <h4 class="text-white"><%= @profile.nickname %></h4>
    <%else%>
        <h4 class="text-white"><%= @profile.email %></h4>
    <%end%>

    <%if(@profile.about_me)%>
        <h5 class="text-white">Описание:</h5>
        <p class="text-white"><%= @profile.about_me %><p>
    <%end%>
</h4>


<% if (current_user)%>
    <% if (current_user.id == @profile.id)%>
        <%= link_to "Редактировать профиль", edit_profile_path(@profile), class: "btn btn-outline-danger"%>
    <%end%>
<%end%>
</div>
<hr>

<div class="container"><h4 class="text-white">Темы:</h4> </div>
<div class="row text-white">
    <% @profile.autos.each do |auto| %>
        
        <div class = "col-md-4 text-left my-4 text-white">
                    <%=link_to auto_path(auto) do%>
                        <%= image_tag auto.image.url(:thumb), class: 'img-show w-100' if auto.image? %>
                    <%end%>
                    <%= link_to "#{auto.title}", auto_path(auto), class: "text-white"%>
                    <br>
                    <small class="text-white"> Автор: 
                    <%if(User.find(auto.user_id).nickname)%>
                        <%=link_to "#{User.find(auto.user_id).nickname}", profile_path(User.find(auto.user_id)), class: "text-white" %>
                    <%else%>
                        <%=link_to "#{User.find(auto.user_id).email}", profile_path(User.find(auto.user_id)), class: "text-white" %>
                    <%end%>
                    </small>
        </div>
    <% end%>
</div>